CREATE DATABASE IF NOT EXISTS medical_data_standardisation CHARACTER SET utf8mb4;
USE medical_data_standardisation;

DROP TABLE IF EXISTS standardized_records;
CREATE TABLE standardized_records (
    `id` VARCHAR(64) PRIMARY KEY,
    `document_id` VARCHAR(128) NULL,
    `record_type` VARCHAR(128) NULL,
    `file_gcs_path` VARCHAR(128) NULL,
    `trace_id` VARCHAR(128) NULL,
    `correlation_id` VARCHAR(128) NULL,
    `source_system` VARCHAR(128) NULL,
    `claim_no` VARCHAR(128) NULL,
    `nt_code` VARCHAR(128) NULL,
    `consumer_client_id` VARCHAR(128) NULL,
    `destination_identifier` VARCHAR(128) NULL,
    `patient_name` VARCHAR(128) NULL,
    `age` VARCHAR(128) NULL,
    `gender` VARCHAR(128) NULL,
    `uhid` VARCHAR(128) NULL,
    `hospital_name` VARCHAR(128) NULL,
    `doctor_name` VARCHAR(128) NULL,
    `bill_date` VARCHAR(128) NULL,
    `reports_date` VARCHAR(128) NULL,
    `test_name_canonical` VARCHAR(128) NULL,
    `test_name_original` TEXT NULL,
    `result_value` DOUBLE NULL,
    `result_text` TEXT NULL,
    `unit_canonical` VARCHAR(128) NULL,
    `unit_original` VARCHAR(128) NULL,
    `range_low` DOUBLE NULL,
    `range_high` DOUBLE NULL,
    `range_text` TEXT NULL,
    `test_analytics` VARCHAR(128) NULL,
    `normalization_method` VARCHAR(128) NULL,
    `normalization_confidence` DOUBLE NULL,
    `admission_date` VARCHAR(128) NULL,
    `discharge_date` VARCHAR(128) NULL,
    `diagnosis` TEXT NULL,
    `brief_history` TEXT NULL,
    `general_examinations` TEXT NULL,
    `recommendations` TEXT NULL,
    `hospital_address` TEXT NULL,
    `ward` VARCHAR(128) NULL,
    `post_discharge_advice` TEXT NULL,
    `medicine` VARCHAR(128) NULL,
    `dose` VARCHAR(128) NULL,
    `frequency` VARCHAR(128) NULL,
    `medicine_type` VARCHAR(128) NULL,
    `processed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `ingested_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `basic_info_age` VARCHAR(128) NULL,
    `basic_info_bill_date` VARCHAR(128) NULL,
    `medicine_injections_investigation` TEXT NULL,
    `discharge_medications_dose` VARCHAR(128) NULL,
    `metadetails` TEXT NULL,
    `discharge_medications_frequency` VARCHAR(128) NULL,
    `discharge_medications_medicine` VARCHAR(128) NULL,
    `lab_or_hospital_name` VARCHAR(128) NULL,
    `report_details_page_no` VARCHAR(128) NULL,
    `report_details_range` TEXT NULL,
    `report_details_result` TEXT NULL,
    `report_details_test_analytics` VARCHAR(128) NULL,
    `report_details_test_name` TEXT NULL,
    `report_details_unit` VARCHAR(128) NULL,
    `age_text` VARCHAR(128) NULL,
    `other_med_inj_investigations` TEXT NULL,
    `report_date` VARCHAR(128) NULL,
    `course_during_hospitalisation` TEXT NULL,
    `page_number` VARCHAR(128) NULL,
    `range_text_original` TEXT NULL,
    `medication_dose` VARCHAR(128) NULL,
    `result_text_original` TEXT NULL,
    `medication_frequency` VARCHAR(128) NULL,
    `course_during_hospitalization` TEXT NULL,
    `medication_name` VARCHAR(128) NULL,
    `page_no` VARCHAR(128) NULL,
    `test_name` TEXT NULL,
    `medication_medicine` VARCHAR(128) NULL,
    `result` TEXT NULL,
    `unit` VARCHAR(128) NULL,
    `age_years` VARCHAR(128) NULL,
    `range` TEXT NULL,
    processing_status VARCHAR(16) DEFAULT 'processed',
    duplicate_flag BOOLEAN DEFAULT FALSE,
    error_message TEXT NULL,
    UNIQUE KEY uq_dedupe (claim_no(100), document_id(100), record_type(50), test_name_original(100), medicine(100), id(64))
) ENGINE=InnoDB;

DROP TABLE IF EXISTS ingestion_errors;
CREATE TABLE ingestion_errors (
    error_id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    file_path     VARCHAR(512),
    document_id   VARCHAR(64) NULL,
    stage         VARCHAR(32),        -- ingest | standardize | validate | load
    error_reason  TEXT,
    raw_payload   LONGTEXT,
    occurred_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

DROP TABLE IF EXISTS pipeline_runs;
CREATE TABLE pipeline_runs (
    run_id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    started_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_at     TIMESTAMP NULL,
    files_seen      INT DEFAULT 0,
    files_processed INT DEFAULT 0,
    files_failed    INT DEFAULT 0,
    records_flagged INT DEFAULT 0,
    duplicates_skipped INT DEFAULT 0
) ENGINE=InnoDB;
