HAEMOGLOBIN:
  unit: g/dL
  low: 13.0
  high: 17.0
  outlier_low: 5.0
  outlier_high: 25.0
  Male:
    low: 13.0
    high: 17.0
  Female:
    low: 12.0
    high: 15.0
  Child:
    low: 10.0
    high: 14.0
WHITE_BLOOD_CELL_COUNT:
  unit: cells/cu.mm
  low: 4000.0
  high: 11000.0
  outlier_low: 500.0
  outlier_high: 50000.0
SERUM_CREATININE:
  unit: mg/dL
  low: 0.66
  high: 1.25
SODIUM:
  unit: mmol/L
  low: 135.0
  high: 145.0
  outlier_low: 100.0
  outlier_high: 180.0
POTASSIUM:
  unit: mmol/L
  low: 3.5
  high: 5.0
  outlier_low: 1.5
  outlier_high: 10.0
RBC_COUNT:
  unit: Million/cu.mm
  low: 4.5
  high: 5.5
  outlier_low: 1.5
  outlier_high: 8.0
PLATELET_COUNT:
  unit: /cu.mm
  low: 150000.0
  high: 410000.0
  outlier_low: 10000.0
  outlier_high: 1000000.0
NEUTROPHILS:
  unit: '%'
  low: 40.0
  high: 80.0
  outlier_low: 5.0
  outlier_high: 95.0
LYMPHOCYTES:
  unit: '%'
  low: 20.0
  high: 40.0
  outlier_low: 5.0
  outlier_high: 95.0
PACKED_CELL_VOLUME:
  unit: '%'
  low: 40.0
  high: 50.0
  outlier_low: 10.0
  outlier_high: 70.0
MEAN_CORPUSCULAR_VOLUME:
  unit: fL
  low: 83.0
  high: 101.0
  outlier_low: 50.0
  outlier_high: 130.0
MCH:
  unit: pg
  low: 27.0
  high: 32.0
  outlier_low: 15.0
  outlier_high: 50.0
MCHC:
  unit: g/dL
  low: 31.5
  high: 34.5
  outlier_low: 20.0
  outlier_high: 45.0
RDW:
  unit: '%'
  low: 11.6
  high: 14.0
  outlier_low: 5.0
  outlier_high: 30.0
SGOT:
  unit: U/L
  low: 17.0
  high: 59.0
  outlier_low: 2.0
  outlier_high: 500.0
SGPT:
  unit: U/L
  low: 21.0
  high: 72.0
  outlier_low: 2.0
  outlier_high: 500.0
COVID19:
  validation_type: qualitative
  allowed:
  - Positive
  - Negative
  - Reactive
  - Non Reactive
  - Non-Reactive
HIV:
  validation_type: qualitative
  allowed:
  - Positive
  - Negative
  - Reactive
  - Non Reactive
  - Non-Reactive
WIDAL:
  validation_type: qualitative
  allowed:
  - Positive
  - Negative
  - Reactive
  - Non Reactive
  - Non-Reactive
  - 80
  - 100
  - 1:80
  - 1:160
LACTATE:
  unit: mmol/L
  low: 0.5
  high: 2.2
  outlier_low: 0.1
  outlier_high: 20.0
MEAN_PLATELET_VOLUME:
  unit: FL
  low: 9.0
  high: 13.0
  outlier_low: 6.0
  outlier_high: 20.0
ERYTHROCYTE_THALASSEMIA_MARKER:
  unit: '%'
  low: 0.17
  high: 0.35
  outlier_low: 0.0
  outlier_high: 1.0
LYMPHOCYTE_PERCENTAGE:
  unit: '%'
  low: 40.0
  high: 70.0
  outlier_low: 0.0
  outlier_high: 100.0
EOSINOPHILS:
  unit: '%'
  low: 2.0
  high: 8.0
  outlier_low: 0.0
  outlier_high: 30.0
MONOCYTE_PERCENTAGE:
  unit: '%'
  low: 2.0
  high: 10.0
  outlier_low: 0.0
  outlier_high: 25.0
DENGUE_NS1_ANTIGEN:
  unit: Index
  validation_type: qualitative
  allowed:
  - Negative
  - Equivocal
  - Positive
C_REACTIVE_PROTEIN:
  unit: mg/L
  low: 0.0
  high: 6.0
  outlier_low: 0.0
  outlier_high: 500.0
TYPHI_IGG_IGM_ANTIBODY:
  unit: Qualitative
  validation_type: qualitative
  allowed:
  - Positive
  - Negative
  - Indeterminate
CHLORIDE:
  unit: mmol/L
  low: 98.0
  high: 107.0
  outlier_low: 85.0
  outlier_high: 120.0
SERUM_LIPASE:
  unit: U/L
  low: 23.0
  high: 300.0
  outlier_low: 0.0
  outlier_high: 10000.0
COMPLETE_URINE_EXAMINATION:
  unit: N/A
  validation_type: qualitative
  allowed:
  - Normal
  - Abnormal
PH:
  unit: pH units
  low: 5.0
  high: 7.5
  outlier_low: 4.5
  outlier_high: 8.0
URINE_SPECIFIC_GRAVITY:
  unit: ratio
  low: 1.002
  high: 1.03
  outlier_low: 1.0
  outlier_high: 1.04
AST_TO_ALT_RATIO:
  unit: ratio
  low: 0.0
  high: 1.15
  outlier_low: 0.0
  outlier_high: 2.5
BLOOD_UREA_NITROGEN:
  unit: mg/dL
  low: 6.0
  high: 24.0
  outlier_low: 0.0
  outlier_high: 100.0
COMPLETE_BLOOD_COUNT:
  unit: g/dL
  low: 13.0
  high: 17.0
  outlier_low: 5.0
  outlier_high: 20.0
DIFFERENTIAL_LEUCOCYTIC_COUNT:
  unit: '%'
  low: 0.0
  high: 100.0
  outlier_low: 0.0
  outlier_high: 100.0
BASOPHIL_PERCENTAGE:
  unit: '%'
  low: 0.0
  high: 2.0
  outlier_low: 0.0
  outlier_high: 5.0
TOTAL_LEUCOCYTE_COUNT:
  unit: Cells/cu.mm
  low: 4.0
  high: 11.0
  outlier_low: 0.0
  outlier_high: 100.0
NEUTROPHIL_TO_LYMPHOCYTE_RATIO:
  unit: ratio
  low: 0.78
  high: 3.53
  outlier_low: 0.0
  outlier_high: 10.0
BILIRUBIN_DIRECT:
  unit: mg/dL
  low: 0.0
  high: 0.3
  outlier_low: 0.0
  outlier_high: 1.0
GLOMERULAR_FILTRATION_RATE:
  unit: mL/min/1.73m^2
  low: 60.0
  high: 120.0
  outlier_low: 0.0
  outlier_high: 200.0
FASTING_BLOOD_SUGAR:
  unit: mmol/L
  low: 3.9
  high: 7.1
  outlier_low: 0.0
  outlier_high: 30.0
CRYSTALS:
  unit: Not Provided
S_PARATYPHI_B_H_AGGLUTINATION:
  unit: AGGLUTINATION
  validation_type: qualitative
  allowed:
  - 1:80 and above
  - Negative
MALARIA_VIVAX_ANTIGEN:
  unit: Index
  validation_type: qualitative
  allowed:
  - Positive
  - Negative
URINE_KETONES:
  unit: mmol/L
  validation_type: qualitative
  allowed:
  - Negative
  - Positive
ABSENT_TEST:
  unit: Not Provided
  validation_type: qualitative
  allowed:
  - Present
  - Absent
DIAGNOSTIC_PANEL:
  unit: N/A
  validation_type: qualitative
  allowed:
  - Normal
  - Abnormal
CHORIONIC_VILLUS_SAMPLING:
  unit: Not Provided
  validation_type: qualitative
  allowed:
  - Normal
  - Abnormal
CALCULATED_GLOBULIN:
  unit: g/dL
  low: 2.0
  high: 3.5
  outlier_low: 1.0
  outlier_high: 4.0
ABDOMINAL_PAIN_ASSESSMENT:
  unit: Not Applicable
  validation_type: qualitative
  allowed:
  - Mild
  - Moderate
  - Severe
  - Absent
BLOOD_PRESSURE:
  unit: mmHg
  low: 90.0
  high: 120.0
  outlier_low: 60.0
  outlier_high: 180.0
TOTAL_LEUCOCYTE_COUNT_PERCENTAGE:
  unit: '%'
  low: 40.0
  high: 62.0
  outlier_low: 0.0
  outlier_high: 100.0
VOLUME_OBSERVATION:
  unit: mL
  low: 0.0
  high: 1000.0
  outlier_low: 0.0
  outlier_high: 2000.0
BILIRUBIN_TOTAL:
  unit: umol/L
  low: 0.0
  high: 20.0
  outlier_low: 0.0
  outlier_high: 500.0
LIGHT_MICROSCOPY_EXAMINATION:
  unit: Not Applicable
  validation_type: qualitative
  allowed:
  - Present
  - Absent
  - Not Detected
  - Detected
MALARIA_PARASITE_SCREEN:
  unit: NOT DETECTED/DETECTED
  validation_type: qualitative
  allowed:
  - NOT DETECTED
  - DETECTED
URIC_ACID:
  unit: mg/dL
  low: 3.5
  high: 8.5
  outlier_low: 0.0
  outlier_high: 20.0
LEUCOCYTE_ESTERASE:
  unit: Units
  low: 0.0
  high: 100.0
  outlier_low: 0.0
  outlier_high: 100.0
CENTRIFUGED_SEDIMENT_WET_MOUNT_AND_MICROSCOPY:
  unit: Not Applicable
  validation_type: qualitative
  allowed:
  - Normal
  - Abnormal
  - Presence of cells or organisms
  - Absence of cells or organisms
BLOOD_CULTURE_AND_SENSITIVITY_AEROBIC:
  unit: Not Applicable
  validation_type: qualitative
  allowed:
  - Sensitive
  - Resistant
  - Intermediate
LIVER_FUNCTION_TEST:
  unit: mg/dL
  low: 0.0
  high: 1.2
BILIRUBIN_INDIRECT:
  unit: mg/dL
  low: 0.0
  high: 0.3
  outlier_low: 0.0
  outlier_high: 1.5
COMMENT_RATIO:
  unit: ratio
  low: 2.0
  high: 3.5
  outlier_low: 0.0
  outlier_high: 10.0
ABSOLUTE_LEUCOCYTE_COUNT:
  unit: cells/cu.mm
  low: 4.0
  high: 11.0
  outlier_low: 0.0
  outlier_high: 100.0
HEART_RATE:
  unit: beats per minute
  low: 60.0
  high: 100.0
  outlier_low: 40.0
  outlier_high: 120.0
'9_11':
  unit: g/dL
  low: 7.0
  high: 15.5
  outlier_low: 0.0
  outlier_high: 20.0
GAMMA_GLUTAMYL_TRANSPEPTIDASE:
  unit: U/L
  low: 8.0
  high: 60.0
  outlier_low: 0.0
  outlier_high: 1000.0
CRYSTALS_LIGHT_MICROSCOPY:
  unit: Not Provided
  validation_type: qualitative
  allowed:
  - Present
  - Absent
CALCIUM:
  unit: mg/dL
  low: 8.4
  high: 10.2
INORGANIC_PHOSPHORUS:
  unit: mg/dL
  low: 2.5
  high: 4.5
PERCENTAGE_OF_ASPYRATED_HAEMOGLOBIN:
  unit: '%'
  low: 0.0
  high: 100.0
  outlier_low: 0.0
  outlier_high: 100.0
OXYGEN_SATURATION:
  unit: '%'
  low: 90.0
  high: 100.0
  outlier_low: 0.0
  outlier_high: 100.0
PHOSPHORUS_SERUM:
  unit: mg/dL
  low: 3.0
  high: 4.5
  outlier_low: 0.0
  outlier_high: 10.0
